<?php
print "<h2>";
printf(_("Install"));
print "</h2>";
print "<h3>";
printf(_("To get all sources"));
print "</h3>";
print "<pre>";
print "wget https://github.com/Open-UDC/open-udc/archive/v0.2.0.tar.gz" ;
print "</pre>";
print "<h3>";
printf(_("Install Lud: OpenUDC command line client"));
print "</h3>";
print "<p>";
printf(_("Get sources"));
print "</p>";
print "<pre>";
print "git clone https://github.com/Open-UDC/lud" ;
print "</pre>";
print "<pre>";
print "cd lud" ;
print "</pre>";
print "<p>";
printf(_("Run as root"));
print "</p>";
print "<pre>";
print "sudo make install" ;
print "</pre>";
print "<p>";
printf(_("Now run as normal user:"));
print "</p>";
print "<pre>";
print "lud.sh" ;
print "</pre>";
print "<ul>";
print "<li>";
printf(_("It asks you informations (place of birth, date of birth, last name, first name) in order to generate a unique ID for your key."));
print "</li>";
print "<li>";
printf(_("When your key is generated, it shows a menu. "));
print "</li>";
print "<li>";
printf(_("Choose 1 to share your KEY with an OpenUDC community Node "));
print "</li>";
print "</ul>";
print "<p>";
printf(_("Launching the program \"seahorse\" you can see your key."));
print "</p>";
print "<h3>";
printf(_("Install OpenUDC Node (ludd)"));
print "</h3>";
print "<p>";
printf(_("Prepare depends"));
print "</p>";
print "<pre>";
print "apt-get install libgpgme11-dev" ;
print "</pre>";
print "<p>";
printf(_("Get sources"));
print "</p>";
print "<pre>";
print "git clone https://github.com/Open-UDC/thttpgpd" ;
print "</pre>";
print "<p>";
printf(_("Install"));
print "</p>";
print "<pre>";
print "cd thttpgpd" ;
print "</pre>";
print "<pre>";
print "./configure --enable-OpenUDC" ;
print "</pre>";
print "<pre>";
print "make" ;
print "</pre>";
print "<pre>";
print "make install" ;
print "</pre>";
print "<p>";
printf(_("Check that /usr/local/var/ludd is created (show hidden file to see it) "));
print "</p>";
print "<pre>";
print "ls -a /usr/local/var/ludd" ;
print "</pre>";
print "<p>";
printf(_("Type the command :"));
print "</p>";
print "<pre>";
print "ludd_init.sh" ;
print "</pre>";
print "<pre>";
print "ludd" ;
print "</pre>";
print "<p>";
printf(_("You can check your local adress : http://127.0.0.1:11371/ and so access to your OpenUDC LUDD node "));
print "</p>";
?>
