<?php
print "<h2>";
printf(_("Contribute to OpenUDC"));
print "</h2>";
print "<p>";
printf(_("The project is still young, we need a lot of contributors for improving it. Feel free to join our developer and user community."));
print "</p>";
print "<h3>";
printf(_("Support"));
print "</h3>";
print "<ul>";
print "<li>";
printf(_("talk about OpenUDC, post on your blog, add a link <a href=\"http://openudc.org\">http://openudc.org</a> on your website, ..."));
print "</li>";
print "<li>";
printf(_("organise an event: talk, key signing party, coding party..."));
print "</li>";
print "<li>";
printf(_("support development team on <a href=\"https://www.gittip.com/OpenUDC/\">https://www.gittip.com/OpenUDC</a> (waiting a free money!)."));
print "</li>";
print "</ul>";
print "<h3>";
printf(_("Develop"));
print "</h3>";
print "<p>";
printf(_("Welcome, developer! Fork on github, submit a project, ..."));
print "</p>";
print "<p>";
printf(_("Github <a href=\"https://github.com/Open-UDC\">https://github.com/Open-UDC</a>"));
print "</p>";
print "<p>";
printf(_("Bug trackers <a href=\"https://github.com/Open-UDC/open-udc/issues\">https://github.com/Open-UDC/open-udc/issues</a>"));
print "</p>";
$coment=sprintf(_("Project structure. Clickable Picture."));
get_image("graph/structure","svg","80%",$coment );
print "<h3>";
printf(_("Translation"));
print "</h3>";
print "<p>";
printf(_("To translate, we use Transifex : <a href=\"https://www.transifex.com/organization/OpenUDC/dashboard\">https://www.transifex.com/organization/OpenUDC/dashboard</a>."));
print "</p>";
print "<p>";
printf(_("Subscribe as translator on Transifex <a href=\"https://www.transifex.com/signup/contributor/\">https://www.transifex.com/signup/contributor/</a>."));
print "</p>";
print "<p>";
printf(_("Ask to join a team for each project and each language, or ask for a new language."));
print "</p>";
?>
